---
abstract: 'Manipulate physics units and dimensions.'
author:
  - 'Christopher Maloney <voldrani@gmail.com>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Physics-Unit
provides:
  Physics::Unit:
    file: lib/Physics/Unit.pm
    version: 0.51
  Physics::Unit::Scalar:
    file: lib/Physics/Unit/Scalar.pm
    version: 0.51
  Physics::Unit::Script:
    file: lib/Physics/Unit/Script.pm
    version: 0.51
  Physics::Unit::Script::GenPages:
    file: lib/Physics/Unit/Script/GenPages.pm
    version: 0
requires:
  warnings: 0
resources:
  bugtracker: https://github.com/Klortho/Physics-Unit/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/Klortho/Physics-Unit
version: 0.51
